#!/bin/bash
if [ ! `which qmake-qt5` ]; then
  echo "You must first install qt5-devel"
  echo "...on fedora:"
  echo "  sudo dnf -y install make gcc-c++ gdb qt5*-devel"
  exit 1
fi
package_name="outputinspector"
makefile_name="Makefile"
# pro_name="outputinspector.pro"
# remove Makefile, since in .gitignore, and generated by pro file:
rm Makefile
if [ ! -f "$makefile_name" ]; then
  echo "creating Makefile..."
  # normally pro file can be specified as param after options, but not needed since detected:
  qmake-qt5 -o $makefile_name
else
  echo "using existing $makefile_name"
fi
build_config="Debug"
release_flag="QT_NO_DEBUG"
echo "detecting configuration by checking $makefile_name for $release_flag..."
if grep -q $release_flag "$makefile_name"; then
  build_config="Release"
fi
echo "detected configuration: $build_config"
pro_dir=`pwd`
build_dir_rel="../build-$package_name-Desktop-$build_config"
if [ ! -d "$build_dir_rel" ]; then
  mkdir "$build_dir_rel"
fi
make
#doesn't work for some reason:
#cd $build_dir_rel
#echo "in `pwd`..."
#make $pro_dir
if [ -f "$package_name" ]; then
  mv -f $package_name "$build_dir_rel/"
fi
build_artifact="moc_predefs.h"
if [ -f "$build_artifact" ]; then
  mv -f "$build_artifact" "$build_dir_rel/"
fi
if [ -f "$build_dir_rel/$package_name" ]; then
  echo "successfully built $build_dir_rel/$package_name"
  echo "run install to install $package_name"
else
  echo "failed to build $build_dir_rel/$package_name"
fi
#cd $pro_dir
